Feature/add profiling support
RidgeRun/templates-meson-standard-gstreamer pull request #3
Opened 2020-03-06 21:35 UTC by fasm22

2020-03-06 21:43 UTC, michaelgruner requested changes

2020-03-06 21:43 UTC, michaelgruner commented on meson.build
> +    error('MESON_SKIP gperftools profiling library not found.')
If the user enabled it, we should fail instead of skipping.

2020-03-06 21:43 UTC, mleivaf requested changes

2020-03-06 21:43 UTC, mleivaf commented on meson_options.txt
> +option('profiling', type : 'feature', value : 'disabled', yield : true, description: 'Enable profiling building')
Could we change the parameter name to `enable-profiling`?

2020-03-06 21:43 UTC, mleivaf commented on meson.build
> +    test_deps=[gst_dep, gst_base_dep, gst_check_dep, profiler_dep]
Can we add only the new dependency to the list of default dependencies?
For example
`test_deps+=profiler_dep`

2020-03-06 21:49 UTC, mleivaf requested changes
Can we create a special definition for profiling? in order to use this definition to enable conditional code.

2020-03-11 15:18 UTC, michaelgruner approved these changes

2020-09-22 16:51 UTC, merged